---
- name: Add the yarn repository key
  apt_key: url={{ yarn_repo_apt_key }} state=present

- name: Add yarn repository
  apt_repository: repo='{{ yarn_repo }}' state=present

- name: Add yarn package
  apt: pkg=yarn state=present
